"""some changes

Revision ID: 63436c6539fa
Revises: b99543b7ce9a
Create Date: 2020-07-15 07:18:48.997864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63436c6539fa'
down_revision = 'b99543b7ce9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    # ### end Alembic commands ###
