"""second vocab

Revision ID: 69386eb05d9c
Revises: a26f939b4dda
Create Date: 2020-07-14 22:01:56.465612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69386eb05d9c'
down_revision = 'a26f939b4dda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dvocab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('words_es', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dvocab')
    # ### end Alembic commands ###
