"""some changes

Revision ID: 6bbc7a982036
Revises: ffa77ce46885
Create Date: 2020-07-15 07:29:15.512897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bbc7a982036'
down_revision = 'ffa77ce46885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'association', 'vocab', ['vocab_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'association', type_='foreignkey')
    # ### end Alembic commands ###
