"""some changes

Revision ID: b99543b7ce9a
Revises: 9a54a160a5d7
Create Date: 2020-07-15 07:05:41.830690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b99543b7ce9a'
down_revision = '9a54a160a5d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('words_es', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vocab')
    # ### end Alembic commands ###
