"""empty message

Revision ID: f82b5fe93062
Revises: 90990fe0ec5a
Create Date: 2020-07-15 19:04:44.063507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f82b5fe93062'
down_revision = '90990fe0ec5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nocab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('words_es', sa.String(length=128), nullable=True),
    sa.Column('form', sa.Integer(), nullable=True),
    sa.Column('def_es', sa.String(length=1000), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('vocab')
    op.create_foreign_key(None, 'association', 'nocab', ['vocab_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'association', type_='foreignkey')
    op.create_table('vocab',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('words_es', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('nocab')
    # ### end Alembic commands ###
