"""some changes

Revision ID: ffa77ce46885
Revises: 63436c6539fa
Create Date: 2020-07-15 07:19:37.608151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffa77ce46885'
down_revision = '63436c6539fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association', sa.Column('vocab_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'association', 'vocab', ['vocab_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'association', type_='foreignkey')
    op.drop_column('association', 'vocab_id')
    # ### end Alembic commands ###
